// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecControlActionPayload } from "./ExecControlActionPayload";

export type ExecControlRequest = { session_id: number, action: ExecControlActionPayload, };
