// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecControlActionPayload = { "type": "keepalive", extend_timeout_ms: bigint | null, } | { "type": "send_ctrl_c" } | { "type": "terminate" } | { "type": "force_kill" } | { "type": "set_idle_timeout", timeout_ms: bigint, } | { "type": "watch", pattern: string, watch_action: string | null, persist: boolean, cooldown_ms: bigint | null, auto_send_ctrl_c: boolean | null, } | { "type": "unwatch", pattern: string, };
