// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecCommandStatus } from "./ExecCommandStatus";
import type { ExecPatternMatchPayload } from "./ExecPatternMatchPayload";

export type ExecCommandPayload = { version: number, status: ExecCommandStatus, session_id: number | null, exit_code: number | null, wall_time_ms: bigint, output: string, truncated: boolean, total_output_bytes: bigint, original_token_count: bigint | null, log_path: string | null, log_sha256: string | null, management_hint: string | null, note: string | null, guidance: string | null, 
/**
 * Number of lines in this response chunk
 */
lines_count: number, 
/**
 * Bytes in this response chunk (before truncation)
 */
chunk_bytes: bigint, 
/**
 * Whether stop_pattern was matched (auto-terminated)
 */
pattern_matched: boolean, pattern_metadata: ExecPatternMatchPayload | null, tail_label: string | null, actions_summary: Array<string> | null, 
/**
 * Whether this is incremental read (cursor advanced)
 */
incremental: boolean, 
/**
 * Start line number (0-indexed)
 */
from_line: bigint, 
/**
 * End line number (exclusive)
 */
to_line: bigint, 
/**
 * Total lines written to session (including evicted)
 */
total_lines: bigint, 
/**
 * Whether output was compressed
 */
compressed: boolean, 
/**
 * Original line count before compression
 */
original_line_count: number, };
