// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecPatternMatchPayload = { pattern: string, matched_line_no: bigint | null, matched_text: string | null, };
